#!/bin/bash
echo "ALX"
^C
root@83bcf6b8506e:/alx-pre_course/0x01-git# bash# clear
root@83bcf6b8506e:/alx-pre_course/0x01-git# bash# cat > school
#!/bin/bash
echo "ALX"
root@83bcf6b8506e:/alx-pre_course/0x01-git# ls
root@83bcf6b8506e:/# cd alx-pre_course
#!/bin/bash
echo "ALX
#!/bin/bash
echo "ALX School is so cool!"
